on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          
      - run: npm ci
        
      - name: Install Dependencies
        run: npm install
      
      - name: Build Application
        run: npm run build

      - name: Zip Files
        uses: vimtor/action-zip@v1.1
        with: 
              files: dist/ node_modules/ package.json
              dest: dist.zip
              recursive: false

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: dist.zip
          destination_dir: LambdaFunctionSource

      - name: Update Lambda Function
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: fastifyLambdaApplication
          s3_bucket: ${{ secrets.AWS_BUCKET }}
          s3_key: LambdaFunctionSource/dist.zip
          handler: dist/lambda.handler
          debug: true


